name: Release

on:
  workflow_run:
    workflows: ["build"]
    branches: ["master"]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.21.3

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: Version release
          title: Next release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
